apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: mywebserver
    newName: IMAGE_NAME
    newTag: IMAGE_TAG
availabilityZones: 
  - us-east-1c
  - us-east-1d
