name: Build documentation

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
  
 
    steps:
    - uses: actions/checkout@v1
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        repository: lanrell/ssc
        tag_with_sha: true
      
    
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIA3LTHPFHCKMID5Z7N
          aws-secret-access-key: /bPpMPrC752oqjNtdMlKFxz2mhFJmIclrehc7Kfw
          aws-region: us-east-1
          aws-session-token: FwoGZXIvYXdzEBcaDGFINnN7TrudcLD30CLMARfXfk7BFNVjLzHBXXoqGac26/Wd5mXhrZ1b5YGB4nfp8XyDIQQczDcpD2FEeFbAwNVDopZ6lbCo84ibrjGJ6+p/+Tz+Nn6pgN+eUnPN91PzWoZsnKSPu8HliJVK16IXjExEIPxble0NywXEPh5JcDk1HFCbYTZvYgi2eren3TzjX646HrBecOpOT/F6CKxPYv63KuM4h6SF+3I4835Ksh7/dlNUtFGblteliPkruC6XLYfUDkMULDzDoeBGIIthpQeSelbirdis8WWj2Si46vv0BTItsHSfM0enaeIHKKXpLPvZ6uI1xXV20FIEXUZHb2GRWq2Z9t1Uwa7MCnwhwlsT
      - name: Deploy App Stack
        id: deploy
        uses: alexjurkiewicz/cfn-deploy@v2.0.1
        with:
          stackName: sylvain-stack
          templateFile: template.yml
      - name: Print App Hostname
        run: echo ${{ steps.deploy.outputs.cf_output_AppHostname }}
      - name: eks
        run: |
         sed -i "s#IMAGE_NAME#lanrell/ssc#g" kustomization.yaml
         sed -i "s/IMAGE_TAG/sha-$(git rev-parse --short HEAD)/g" kustomization.yaml
         aws eks update-kubeconfig --name isen
         kubectl kustomize . | kubectl apply -f -
