name: Build documentation

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
  
 
    steps:
    - uses: actions/checkout@v1
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        repository: lanrell/ssc
        tag_with_sha: true
      
    - name: eks
      run: |
        sed -i "s#IMAGE_NAME#<add-your-image-name-here>#g" kustomization.yaml
        sed -i "s/IMAGE_TAG/sha-$(git rev-parse --short HEAD)/g" kustomization.yaml
        aws eks update-kubeconfig --name isen
        kubectl kustomize . | kubectl apply -f -
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIA3LTHPFHCB7GORD4J
          aws-secret-access-key: fK1oXVq0n473bprHXKv7GN+FSNcyr92R8gIoIfYi
          aws-region: us-east-1
          aws-session-token: FwoGZXIvYXdzEBIaDA6ItA1dNc/lag/82SLMARU7a6CbTyIzpxzTgcCPg1WkjFF8Qvp1apYkhBlo8EY47ZyKZKjTW77DMATaPqA7nkMLCsln+OEKByKADZcrccUC3ZVD0JQLmZMHbQfKYyBYqzFc+ldtJji9weFcfpYhpPbLgZgu7Ilv05u3hQ0fZh4JFxaUbNjhoHSCWrThIsr9gUrge11Lwvktq0sGbmbz3UIYpsuRvq6RSmogvCCKltgrLyjkZmWiwydWpE8G/yxnLLbqiaoxI8EjjwY7P3ndBIT+hvKRbC+K8LasJyiu4/r0BTItGzfai8wSDTeFUeysmwDAnitHRVdJmKTwiuaOdfJ7aADDa7rCFpl5Gurum39z
      - name: Deploy App Stack
        id: deploy
        uses: alexjurkiewicz/cfn-deploy@v2.0.1
        with:
          stackName: sylvain-stack
          templateFile: template.yml
      - name: Print App Hostname
        run: echo ${{ steps.deploy.outputs.cf_output_AppHostname }}
